// Research tree definitions
// 5 branches × ~8 nodes = 40 nodes
// Each node: { id, name, desc, branch, cost (RP), time (seconds), effects, requires (node ids) }
// Effects use same types as upgrades plus research-specific ones

export const RESEARCH_BRANCHES = [
  { id: 'agriculture', name: 'Agriculture', icon: '🌾', color: 'var(--food)', desc: 'Mastery of the cursed soil' },
  { id: 'industry', name: 'Industry', icon: '⚒', color: 'var(--stone)', desc: 'Forge and furnace, wood and stone' },
  { id: 'commerce', name: 'Commerce', icon: '⚖', color: 'var(--gold)', desc: 'The flow of coin through shadow' },
  { id: 'military', name: 'Military', icon: '⚔', color: 'var(--iron)', desc: 'Strength against the darkness' },
  { id: 'theology', name: 'Theology', icon: '✟', color: 'var(--faith)', desc: 'Whispers of the forgotten gods' },
]

export const RESEARCH_NODES = [
  // ═══ Agriculture ═══
  {
    id: 'agri_1',
    name: 'Crop Rotation',
    desc: '+25% Farm production',
    branch: 'agriculture',
    cost: 10,
    time: 30,
    effects: [{ type: 'building_mult', target: 'farm', value: 1.25 }],
    requires: [],
  },
  {
    id: 'agri_2',
    name: 'Irrigation',
    desc: '+50% Farm production',
    branch: 'agriculture',
    cost: 25,
    time: 60,
    effects: [{ type: 'building_mult', target: 'farm', value: 1.5 }],
    requires: ['agri_1'],
  },
  {
    id: 'agri_3',
    name: 'Granary Expansion',
    desc: '+5K food storage',
    branch: 'agriculture',
    cost: 20,
    time: 45,
    effects: [{ type: 'storage_resource', target: 'food', value: 5000 }],
    requires: ['agri_1'],
  },
  {
    id: 'agri_4',
    name: 'Selective Breeding',
    desc: '+100% Farm production',
    branch: 'agriculture',
    cost: 60,
    time: 120,
    effects: [{ type: 'building_mult', target: 'farm', value: 2 }],
    requires: ['agri_2'],
  },
  {
    id: 'agri_5',
    name: 'Harvest Festival',
    desc: 'Harvest click mode +50%',
    branch: 'agriculture',
    cost: 40,
    time: 90,
    effects: [{ type: 'mode_mult', target: 'harvest', value: 1.5 }],
    requires: ['agri_2'],
  },
  {
    id: 'agri_6',
    name: 'Fertile Enchantment',
    desc: '+25K food storage',
    branch: 'agriculture',
    cost: 80,
    time: 150,
    effects: [{ type: 'storage_resource', target: 'food', value: 25000 }],
    requires: ['agri_3', 'agri_4'],
  },
  {
    id: 'agri_7',
    name: 'Bountiful Curse',
    desc: '+2% all production per Farm level',
    branch: 'agriculture',
    cost: 120,
    time: 240,
    effects: [{ type: 'global_per_level', per: 'farm', value: 0.02 }],
    requires: ['agri_4', 'agri_5'],
  },
  {
    id: 'agri_cap',
    name: 'Cornucopia',
    desc: 'Farms produce all resources at 10% rate',
    branch: 'agriculture',
    cost: 200,
    time: 360,
    effects: [{ type: 'farm_all_resources', value: 0.1 }],
    requires: ['agri_6', 'agri_7'],
    capstone: true,
  },

  // ═══ Industry ═══
  {
    id: 'ind_1',
    name: 'Improved Tools',
    desc: '+25% Lumber Mill & Quarry production',
    branch: 'industry',
    cost: 10,
    time: 30,
    effects: [
      { type: 'building_mult', target: 'lumber_mill', value: 1.25 },
      { type: 'building_mult', target: 'quarry', value: 1.25 },
    ],
    requires: [],
  },
  {
    id: 'ind_2',
    name: 'Deep Mining',
    desc: '+50% Mine production',
    branch: 'industry',
    cost: 25,
    time: 60,
    effects: [{ type: 'building_mult', target: 'mine', value: 1.5 }],
    requires: ['ind_1'],
  },
  {
    id: 'ind_3',
    name: 'Cost Reduction',
    desc: '-10% building costs',
    branch: 'industry',
    cost: 30,
    time: 75,
    effects: [{ type: 'building_cost_mult', value: 0.9 }],
    requires: ['ind_1'],
  },
  {
    id: 'ind_4',
    name: 'Steel Forging',
    desc: '+100% Mine production',
    branch: 'industry',
    cost: 60,
    time: 120,
    effects: [{ type: 'building_mult', target: 'mine', value: 2 }],
    requires: ['ind_2'],
  },
  {
    id: 'ind_5',
    name: 'Precision Cutting',
    desc: '+75% Lumber Mill production',
    branch: 'industry',
    cost: 50,
    time: 100,
    effects: [{ type: 'building_mult', target: 'lumber_mill', value: 1.75 }],
    requires: ['ind_2'],
  },
  {
    id: 'ind_6',
    name: 'Advanced Metallurgy',
    desc: '+25K iron & stone storage',
    branch: 'industry',
    cost: 70,
    time: 135,
    effects: [
      { type: 'storage_resource', target: 'iron', value: 25000 },
      { type: 'storage_resource', target: 'stone', value: 25000 },
    ],
    requires: ['ind_4'],
  },
  {
    id: 'ind_7',
    name: 'Mass Production',
    desc: '-20% building costs',
    branch: 'industry',
    cost: 100,
    time: 200,
    effects: [{ type: 'building_cost_mult', value: 0.8 }],
    requires: ['ind_3', 'ind_5'],
  },
  {
    id: 'ind_cap',
    name: 'Dwarven Forge',
    desc: 'Mine Strike click gives 3× resources',
    branch: 'industry',
    cost: 200,
    time: 360,
    effects: [{ type: 'mode_mult', target: 'mine_strike', value: 3 }],
    requires: ['ind_6', 'ind_7'],
    capstone: true,
  },

  // ═══ Commerce ═══
  {
    id: 'com_1',
    name: 'Barter System',
    desc: '+25% Market production',
    branch: 'commerce',
    cost: 10,
    time: 30,
    effects: [{ type: 'building_mult', target: 'market', value: 1.25 }],
    requires: [],
  },
  {
    id: 'com_2',
    name: 'Currency Reform',
    desc: '+50% Market production',
    branch: 'commerce',
    cost: 25,
    time: 60,
    effects: [{ type: 'building_mult', target: 'market', value: 1.5 }],
    requires: ['com_1'],
  },
  {
    id: 'com_3',
    name: 'Royal Treasury',
    desc: '+10K gold storage',
    branch: 'commerce',
    cost: 20,
    time: 45,
    effects: [{ type: 'storage_resource', target: 'gold', value: 10000 }],
    requires: ['com_1'],
  },
  {
    id: 'com_4',
    name: 'Trade Caravans',
    desc: '+100% Market production',
    branch: 'commerce',
    cost: 60,
    time: 120,
    effects: [{ type: 'building_mult', target: 'market', value: 2 }],
    requires: ['com_2'],
  },
  {
    id: 'com_5',
    name: 'Tax Collection',
    desc: 'Royal Decree click +100%',
    branch: 'commerce',
    cost: 40,
    time: 90,
    effects: [{ type: 'mode_mult', target: 'decree', value: 2 }],
    requires: ['com_2'],
  },
  {
    id: 'com_6',
    name: 'Merchant Guild',
    desc: '+3% Market per total building level',
    branch: 'commerce',
    cost: 80,
    time: 160,
    effects: [{ type: 'synergy_total', source: 'market', value: 0.03 }],
    requires: ['com_4'],
  },
  {
    id: 'com_7',
    name: 'Grand Vault',
    desc: '+100K gold storage',
    branch: 'commerce',
    cost: 100,
    time: 200,
    effects: [{ type: 'storage_resource', target: 'gold', value: 100000 }],
    requires: ['com_3', 'com_5'],
  },
  {
    id: 'com_cap',
    name: 'Golden Age',
    desc: '+5% all production per Market level',
    branch: 'commerce',
    cost: 200,
    time: 360,
    effects: [{ type: 'global_per_level', per: 'market', value: 0.05 }],
    requires: ['com_6', 'com_7'],
    capstone: true,
  },

  // ═══ Military ═══
  {
    id: 'mil_1',
    name: 'Basic Training',
    desc: '+10% crit chance',
    branch: 'military',
    cost: 10,
    time: 30,
    effects: [{ type: 'crit_chance_flat', value: 0.10 }],
    requires: [],
  },
  {
    id: 'mil_2',
    name: 'Weapon Mastery',
    desc: '×2 crit damage',
    branch: 'military',
    cost: 25,
    time: 60,
    effects: [{ type: 'crit_mult', value: 2 }],
    requires: ['mil_1'],
  },
  {
    id: 'mil_3',
    name: 'Fortifications',
    desc: 'Reduce negative event damage by 30%',
    branch: 'military',
    cost: 20,
    time: 45,
    effects: [{ type: 'event_defense', value: 0.3 }],
    requires: ['mil_1'],
  },
  {
    id: 'mil_4',
    name: 'Elite Guard',
    desc: '+15% crit chance',
    branch: 'military',
    cost: 60,
    time: 120,
    effects: [{ type: 'crit_chance_flat', value: 0.15 }],
    requires: ['mil_2'],
  },
  {
    id: 'mil_5',
    name: 'Siege Engineering',
    desc: '×3 click power',
    branch: 'military',
    cost: 50,
    time: 100,
    effects: [{ type: 'click_mult', value: 3 }],
    requires: ['mil_2'],
  },
  {
    id: 'mil_6',
    name: 'Castle Walls',
    desc: 'Reduce negative event damage by 50%',
    branch: 'military',
    cost: 70,
    time: 135,
    effects: [{ type: 'event_defense', value: 0.5 }],
    requires: ['mil_3'],
  },
  {
    id: 'mil_7',
    name: 'War Machine',
    desc: '×5 crit damage',
    branch: 'military',
    cost: 100,
    time: 200,
    effects: [{ type: 'crit_mult', value: 5 }],
    requires: ['mil_4', 'mil_5'],
  },
  {
    id: 'mil_cap',
    name: 'Conqueror',
    desc: 'All clicks have +25% crit chance and ×10 crit damage',
    branch: 'military',
    cost: 200,
    time: 360,
    effects: [
      { type: 'crit_chance_flat', value: 0.25 },
      { type: 'crit_mult', value: 10 },
    ],
    requires: ['mil_6', 'mil_7'],
    capstone: true,
  },

  // ═══ Theology ═══
  {
    id: 'theo_1',
    name: 'Prayer Chants',
    desc: '+50% Chapel production',
    branch: 'theology',
    cost: 10,
    time: 30,
    effects: [{ type: 'building_mult', target: 'chapel', value: 1.5 }],
    requires: [],
  },
  {
    id: 'theo_2',
    name: 'Sacred Texts',
    desc: 'Prayer click mode +100%',
    branch: 'theology',
    cost: 25,
    time: 60,
    effects: [{ type: 'mode_mult', target: 'prayer', value: 2 }],
    requires: ['theo_1'],
  },
  {
    id: 'theo_3',
    name: 'Reliquary',
    desc: '+10K faith storage',
    branch: 'theology',
    cost: 20,
    time: 45,
    effects: [{ type: 'storage_resource', target: 'faith', value: 10000 }],
    requires: ['theo_1'],
  },
  {
    id: 'theo_4',
    name: 'Divine Inspiration',
    desc: '+100% Chapel production',
    branch: 'theology',
    cost: 60,
    time: 120,
    effects: [{ type: 'building_mult', target: 'chapel', value: 2 }],
    requires: ['theo_2'],
  },
  {
    id: 'theo_5',
    name: 'Pilgrimage Routes',
    desc: '+2% all production per Chapel level',
    branch: 'theology',
    cost: 50,
    time: 100,
    effects: [{ type: 'global_per_level', per: 'chapel', value: 0.02 }],
    requires: ['theo_2'],
  },
  {
    id: 'theo_6',
    name: 'Holy Relics',
    desc: '+50K faith storage',
    branch: 'theology',
    cost: 80,
    time: 150,
    effects: [{ type: 'storage_resource', target: 'faith', value: 50000 }],
    requires: ['theo_3', 'theo_4'],
  },
  {
    id: 'theo_7',
    name: 'Miracle Workers',
    desc: '+50% momentum gain, -25% momentum decay',
    branch: 'theology',
    cost: 100,
    time: 200,
    effects: [
      { type: 'momentum_gain_mult', value: 1.5 },
      { type: 'momentum_decay_mult', value: 0.75 },
    ],
    requires: ['theo_4', 'theo_5'],
  },
  {
    id: 'theo_cap',
    name: 'Apotheosis',
    desc: '+50% crown bonus on prestige',
    branch: 'theology',
    cost: 200,
    time: 360,
    effects: [{ type: 'crown_bonus', value: 1.5 }],
    requires: ['theo_6', 'theo_7'],
    capstone: true,
  },
]

// Lookup map
export const RESEARCH_MAP = Object.fromEntries(RESEARCH_NODES.map(n => [n.id, n]))
