// Upgrade definitions
// effects: array of { type, target?, value } objects
// Effect types:
//   click_mult        — multiplies click power (stacks multiplicatively)
//   building_mult     — multiplies a building's production (target = building id)
//   storage_flat      — adds flat amount to all resource caps
//   momentum_gain_mult — multiplies momentum gain per click
//   momentum_decay_mult — multiplies momentum decay rate (< 1 = slower)
//   crit_chance_flat  — adds flat crit chance (0.03 = +3%)
//   crit_mult         — multiplies crit damage (stacks multiplicatively)
//   synergy           — source building gets +value per level of per building
//   synergy_total     — source building gets +value per total building level
//   global_per_level  — all buildings get +value per level of per building
//   mode_mult         — multiplies click rewards for a specific click mode
//   dual_focus        — top 2 momentum modes don't decay

export const UPGRADE_CATEGORIES = [
  { id: 'click', name: 'Click Power' },
  { id: 'building', name: 'Production' },
  { id: 'storage', name: 'Storage' },
  { id: 'momentum', name: 'Momentum' },
  { id: 'critical', name: 'Critical' },
  { id: 'synergy', name: 'Synergy' },
  { id: 'advanced', name: 'Advanced' },
]

export const UPGRADES = [
  // ═══ Click Power ═══
  {
    id: 'click_1',
    name: 'Hardened Hands',
    desc: 'Calluses from years of dark labor',
    icon: '✊',
    category: 'click',
    cost: { gold: 100 },
    effects: [{ type: 'click_mult', value: 2 }],
    unlock: null,
    requires: [],
  },
  {
    id: 'click_2',
    name: 'Iron Fists',
    desc: 'Knuckles reinforced with cold iron',
    icon: '🤜',
    category: 'click',
    cost: { gold: 1000, iron: 200 },
    effects: [{ type: 'click_mult', value: 2 }],
    unlock: { mine: 1 },
    requires: ['click_1'],
  },
  {
    id: 'click_3',
    name: 'Rune-Forged Arms',
    desc: 'Ancient glyphs empower each strike',
    icon: '💪',
    category: 'click',
    cost: { gold: 5000, iron: 1000 },
    effects: [{ type: 'click_mult', value: 3 }],
    unlock: { blacksmith: 1 },
    requires: ['click_2'],
  },
  {
    id: 'click_4',
    name: "Titan's Grip",
    desc: 'Strength beyond mortal reckoning',
    icon: '👊',
    category: 'click',
    cost: { gold: 25000, iron: 5000, faith: 1000 },
    effects: [{ type: 'click_mult', value: 5 }],
    unlock: { blacksmith: 5 },
    requires: ['click_3'],
  },

  // ═══ Building Efficiency ═══
  {
    id: 'build_farm',
    name: 'Fertile Soil',
    desc: 'Dark earth yields twice the grain',
    icon: '🌱',
    category: 'building',
    cost: { food: 200, gold: 100 },
    effects: [{ type: 'building_mult', target: 'farm', value: 2 }],
    unlock: { farm: 5 },
    requires: [],
  },
  {
    id: 'build_lumber',
    name: 'Sharp Axes',
    desc: 'Blades that never dull',
    icon: '🪓',
    category: 'building',
    cost: { wood: 200, gold: 100 },
    effects: [{ type: 'building_mult', target: 'lumber_mill', value: 2 }],
    unlock: { lumber_mill: 5 },
    requires: [],
  },
  {
    id: 'build_quarry',
    name: 'Deep Quarrying',
    desc: 'Excavation into the bedrock',
    icon: '⛏',
    category: 'building',
    cost: { stone: 500, gold: 200 },
    effects: [{ type: 'building_mult', target: 'quarry', value: 2 }],
    unlock: { quarry: 5 },
    requires: [],
  },
  {
    id: 'build_mine',
    name: 'Vein Seeker',
    desc: 'Follow the glint of ore deeper',
    icon: '⛓',
    category: 'building',
    cost: { iron: 500, gold: 200 },
    effects: [{ type: 'building_mult', target: 'mine', value: 2 }],
    unlock: { mine: 5 },
    requires: [],
  },
  {
    id: 'build_market',
    name: 'Trade Routes',
    desc: 'Caravans brave the cursed roads',
    icon: '🛤',
    category: 'building',
    cost: { gold: 1000, wood: 500 },
    effects: [{ type: 'building_mult', target: 'market', value: 2 }],
    unlock: { market: 5 },
    requires: [],
  },
  {
    id: 'build_chapel',
    name: 'Sacred Incense',
    desc: 'Holy smoke draws the faithful',
    icon: '🕯',
    category: 'building',
    cost: { faith: 500, gold: 500 },
    effects: [{ type: 'building_mult', target: 'chapel', value: 2 }],
    unlock: { chapel: 5 },
    requires: [],
  },

  // ═══ Storage ═══
  {
    id: 'storage_1',
    name: 'Stockpile',
    desc: 'Crude shelters to hoard supplies',
    icon: '📦',
    category: 'storage',
    cost: { gold: 200, wood: 200 },
    effects: [{ type: 'storage_flat', value: 1000 }],
    unlock: null,
    requires: [],
  },
  {
    id: 'storage_2',
    name: 'Storehouses',
    desc: 'Proper storage against the dark',
    icon: '🏚',
    category: 'storage',
    cost: { gold: 2000, stone: 1000 },
    effects: [{ type: 'storage_flat', value: 5000 }],
    unlock: { market: 3 },
    requires: ['storage_1'],
  },
  {
    id: 'storage_3',
    name: 'Warehouses',
    desc: 'Vast halls filled with provisions',
    icon: '🏛',
    category: 'storage',
    cost: { gold: 10000, wood: 5000, stone: 5000 },
    effects: [{ type: 'storage_flat', value: 25000 }],
    unlock: { market: 8 },
    requires: ['storage_2'],
  },
  {
    id: 'storage_4',
    name: 'Vaults of the Deep',
    desc: 'Sealed chambers beneath the earth',
    icon: '🔐',
    category: 'storage',
    cost: { gold: 50000, iron: 25000 },
    effects: [{ type: 'storage_flat', value: 100000 }],
    unlock: { library: 3 },
    requires: ['storage_3'],
  },

  // ═══ Momentum ═══
  {
    id: 'momentum_1',
    name: 'Focus',
    desc: 'Clear mind, stronger intent',
    icon: '🎯',
    category: 'momentum',
    cost: { gold: 300, faith: 100 },
    effects: [{ type: 'momentum_gain_mult', value: 1.5 }],
    unlock: { chapel: 1 },
    requires: [],
  },
  {
    id: 'momentum_2',
    name: 'Concentration',
    desc: 'Unwavering devotion to the task',
    icon: '🧘',
    category: 'momentum',
    cost: { gold: 2000, faith: 500 },
    effects: [{ type: 'momentum_gain_mult', value: 2 }],
    unlock: { chapel: 5 },
    requires: ['momentum_1'],
  },
  {
    id: 'momentum_3',
    name: 'Patience',
    desc: 'Momentum lingers in the darkness',
    icon: '⏳',
    category: 'momentum',
    cost: { gold: 1000, faith: 300 },
    effects: [{ type: 'momentum_decay_mult', value: 0.7 }],
    unlock: { chapel: 3 },
    requires: [],
  },
  {
    id: 'momentum_4',
    name: 'Zen of the Void',
    desc: 'The void sustains your rhythm',
    icon: '🌀',
    category: 'momentum',
    cost: { gold: 5000, faith: 2000 },
    effects: [{ type: 'momentum_decay_mult', value: 0.5 }],
    unlock: { library: 3 },
    requires: ['momentum_3'],
  },

  // ═══ Critical ═══
  {
    id: 'crit_1',
    name: 'Keen Eye',
    desc: 'Spot the weakness in the dark',
    icon: '👁',
    category: 'critical',
    cost: { gold: 500, iron: 200 },
    effects: [{ type: 'crit_chance_flat', value: 0.03 }],
    unlock: { blacksmith: 1 },
    requires: [],
  },
  {
    id: 'crit_2',
    name: 'Sharp Instinct',
    desc: 'Strike before thought forms',
    icon: '🗡',
    category: 'critical',
    cost: { gold: 3000, iron: 1000 },
    effects: [{ type: 'crit_chance_flat', value: 0.05 }],
    unlock: { blacksmith: 5 },
    requires: ['crit_1'],
  },
  {
    id: 'crit_3',
    name: 'Devastating Blow',
    desc: 'A strike that echoes through bone',
    icon: '💥',
    category: 'critical',
    cost: { gold: 2000, iron: 500 },
    effects: [{ type: 'crit_mult', value: 2.5 }],
    unlock: { blacksmith: 3 },
    requires: [],
  },
  {
    id: 'crit_4',
    name: 'Annihilation',
    desc: 'Reduce to dust with a single blow',
    icon: '☠',
    category: 'critical',
    cost: { gold: 15000, iron: 3000 },
    effects: [{ type: 'crit_mult', value: 5 }],
    unlock: { blacksmith: 8 },
    requires: ['crit_3'],
  },

  // ═══ Synergy ═══
  {
    id: 'syn_farm',
    name: 'Farming Commune',
    desc: 'Timber frames increase crop yield',
    icon: '🤝',
    category: 'synergy',
    cost: { food: 500, wood: 500 },
    effects: [{ type: 'synergy', source: 'farm', per: 'lumber_mill', value: 0.02 }],
    unlock: { farm: 5, lumber_mill: 5 },
    requires: [],
  },
  {
    id: 'syn_mine',
    name: 'Mining Guild',
    desc: 'Quarrymen guide the miners deeper',
    icon: '⚒',
    category: 'synergy',
    cost: { iron: 500, stone: 500 },
    effects: [{ type: 'synergy', source: 'mine', per: 'quarry', value: 0.02 }],
    unlock: { mine: 5, quarry: 5 },
    requires: [],
  },
  {
    id: 'syn_market',
    name: 'Trade Federation',
    desc: 'Every building feeds commerce',
    icon: '🏪',
    category: 'synergy',
    cost: { gold: 2000, wood: 1000, stone: 1000 },
    effects: [{ type: 'synergy_total', source: 'market', value: 0.02 }],
    unlock: { market: 10 },
    requires: [],
  },
  {
    id: 'syn_divine',
    name: 'Divine Economy',
    desc: 'Every prayer blesses production',
    icon: '✨',
    category: 'synergy',
    cost: { faith: 2000, gold: 2000 },
    effects: [{ type: 'global_per_level', per: 'chapel', value: 0.01 }],
    unlock: { chapel: 10 },
    requires: [],
  },

  // ═══ Advanced ═══
  {
    id: 'adv_harvest',
    name: 'Double Harvest',
    desc: 'The land yields twice to your hand',
    icon: '🌾',
    category: 'advanced',
    cost: { food: 1000, gold: 500 },
    effects: [{ type: 'mode_mult', target: 'harvest', value: 2 }],
    unlock: { farm: 10 },
    requires: [],
  },
  {
    id: 'adv_mine',
    name: "Prospector's Eye",
    desc: 'See ore veins through solid rock',
    icon: '🔍',
    category: 'advanced',
    cost: { iron: 1000, stone: 1000 },
    effects: [{ type: 'mode_mult', target: 'mine_strike', value: 2 }],
    unlock: { mine: 8 },
    requires: [],
  },
  {
    id: 'adv_prayer',
    name: 'Holy Fervor',
    desc: 'The gods hear you twice as clearly',
    icon: '🙏',
    category: 'advanced',
    cost: { faith: 1000, gold: 500 },
    effects: [{ type: 'mode_mult', target: 'prayer', value: 2 }],
    unlock: { chapel: 8 },
    requires: [],
  },
  {
    id: 'adv_dual',
    name: 'Dual Focus',
    desc: 'Maintain mastery over two disciplines',
    icon: '⚖',
    category: 'advanced',
    cost: { gold: 5000, faith: 3000, iron: 2000 },
    effects: [{ type: 'dual_focus' }],
    unlock: { library: 5, chapel: 5 },
    requires: [],
  },
]

// Lookup map
export const UPGRADE_MAP = Object.fromEntries(UPGRADES.map(u => [u.id, u]))
